CREATE TABLE subscriptions (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
public_id CHAR(36) NOT NULL UNIQUE,
target_url VARCHAR(512) NOT NULL,
event_type VARCHAR(100) NOT NULL,
created_at DATETIME NOT NULL,
active BOOLEAN NOT NULL DEFAULT TRUE
)